### ISSUE TITLE
Potential deadlock issues in ASP.NET context

### ISSUE THREAD

**Issue by rnagpal** [ealsur/concurrentdocdb#1]
There is one issue that I'd like to highlight is that your public APIs are marked with "async" qualifier due to the fact that you are using "await" inside. This will cause deadlock issues when this code is run in ASP.NET context unless someone explicitly calls .ConfigureAwait(false) on the API(which most people don't know).

To fix this, either use .ConfigureAwait(false) in all the await statements within your API or have the public API return a Task or Task<T> without "async" qualifier and wrap the code inside in a private async method. 

Here is an example:

public static Task<ResourceResponse<Document>> ReplaceConcurrentDocumentAsync(this DocumentClient client, Document document, RequestOptions options = null)
{
return InlineIfPossible(() => this.ReplaceConcurrentDocumentPrivateAsync(this client, document, options));
}

private async Task<ResourceResponse<Document>> ReplaceConcurrentDocumentPrivateAsync(this DocumentClient client, Document document, RequestOptions options)
{
// Existing code that you have in ReplaceConcurrentDocumentAsync
}

static public Task InlineIfPossible(Func<Task> function)
        {
            if (SynchronizationContext.Current == null)
            {
                    return function();
            }
            else
            {
                    return Task.Run(function);
            }
        }

You should first try to repro this in an ASP.NET project and verify that the below change fixes it.

The reason I know this is that coincidently, I'm working on fixing the same issue in our .NET SDK APIs

**Comment by ealsur** [comment]
Awesome @rnagpal! Thanks for the details, I will add ASP.NET tests and rewrite the extensions based on your comment.

**Comment by ealsur** [comment]
Just to add some more info in case someone gets here, I also read this MSDN article [Async/Await - Best Practices in Asynchronous Programming](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) to understand the reason in detail.
